language: objective-c
xcode_project: TravisCI/TravisCI.xcodeproj # path to your xcodeproj folder
xcode_scheme: TravisCI
install:
   - bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without development