language: objective-c
cache: bundler
xcode_project: TravisCI/TravisCI.xcodeproj # path to your xcodeproj folder
xcode_scheme: TravisCI
osx_image: xcode8
xctool:
    -workspace cam-pro.xcworkspace -scheme cam-beta clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
# script:
#   - xcodebuild CODE_SIGNING_REQUIRED=NO
install:
   - bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without development